#ifndef SSINPUT_USER_H
#define SSINPUT_USER_H

#define CTRL_SSINPUT_ENABLE				CTL_CODE(FILE_DEVICE_SSINPUT, 1, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define CTRL_SSINPUT_DISABLE			CTL_CODE(FILE_DEVICE_SSINPUT, 2, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define CTRL_SSINPUT_GET_MOUSE_DATA		CTL_CODE(FILE_DEVICE_SSINPUT, 3, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define CTRL_SSINPUT_GET_KBRD_DATA		CTL_CODE(FILE_DEVICE_SSINPUT, 4, METHOD_BUFFERED, FILE_ANY_ACCESS)

#endif
