//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by NetworkLayerTest.rc
//
#define IDD_NETWORKLAYERTEST_DIALOG     102
#define IDR_MAINFRAME                   128
#define IDD_STREAM_FABRIC_TEST          129
#define IDD_MAIN_DIALOG                 130
#define IDR_MENU1                       131
#define IDD_NAT_TRAVERSAL_DIALOG        132
#define IDD_                            133
#define IDD_RELAYED_STREAM_DLG          133
#define IDD_PROGRESS_DLG                134
#define IDC_CONNECT_GROUP               1000
#define IDC_REMOTE_ADDR                 1001
#define IDC_REMOTE_PORT                 1002
#define IDC_LOCAL_PORT                  1003
#define IDC_EDIT_REMOTE_ADDR            1004
#define IDC_EDIT_REMOTE_PORT            1005
#define IDC_EDIT_LOCAL_PORT             1006
#define IDC_PROXY_GROUP                 1007
#define IDC_CHECK_USE_PROXY             1008
#define IDC_PROXY_ADDR                  1009
#define IDC_PROXY_PORT                  1010
#define IDC_EDIT_PROXY_ADDR             1011
#define IDC_EDIT_PROXY_PORT             1012
#define IDC_COMPRESSION_GROUP           1013
#define IDC_CIPHER_GROUP                1014
#define IDC_KEY_GROUP                   1015
#define IDC_RADIO_COMP_NONE             1016
#define IDC_RADIO_COMP_ZLIB             1017
#define IDC_RADIO_COMP_LZO              1018
#define IDC_RADIO_CIPH_NONE             1019
#define IDC_RADIO_CIPH_AES_128          1020
#define IDC_RADIO_CIPH_AES_256          1021
#define IDC_RADIO_3DES                  1022
#define IDC_RADIO_CIPH_RC4_128          1023
#define IDC_RADIO_KX_PSK                1024
#define IDC_RADIO_KX_DHE_PSK            1025
#define IDC_CLIENT_GROUP                1026
#define IDC_CREDENTIALS_GROUP           1026
#define IDC_USER_ID                     1027
#define IDC_USER_KEY                    1028
#define IDC_EDIT_USER_ID                1029
#define IDC_EDIT_USER_KEY               1030
#define IDC_EDIT_SEND_TEXT              1033
#define IDC_CONTROL_GROUP               1034
#define IDC_EDIT_TIMEOUT                1035
#define IDC_TIMEOUT                     1036
#define IDC_BUTTON_CONNECT              1037
#define IDC_BUTTON_DISCONNECT           1038
#define IDC_DATA_GROUP                  1039
#define IDC_BUTTON_SEND                 1040
#define IDC_LIST_SEND                   1041
#define IDC_LIST_RECEIVE                1042
#define IDC_BUTTON_CLEAR                1043
#define IDC_CHECK_ADD_BRAKLINE          1044
#define IDC_LOCAL_PEED_EDIT             1045
#define IDC_REMOTE_PEED_EDIT            1047
#define IDC_MASTER_CHECK                1048
#define IDC_CONNECT_BUTTON              1049
#define IDC_TABCONTROL                  1050
#define IDC_CONNECT_BUTTON2             1050
#define IDC_RESETIM_BUTTON              1050
#define IDC_DISCONNECT_BUTTON           1051
#define IDC_LOG_LIST                    1057
#define IDC_NAT_RELAY_GROUP             1058
#define IDC_NAT_SRV_ADDRESS             1059
#define IDC_EDIT_NAT_SRV_ADDRESS        1060
#define IDC_NAT_SRV_PORT                1061
#define IDC_EDIT_NAT_SRV_PORT           1062
#define IDC_NAT_SRV_CRED_GROUP          1063
#define IDC_NAT_SRV_USER                1064
#define IDC_EDIT_NAT_SRV_USER           1065
#define IDC_NAT_SRV_PASS                1066
#define IDC_EDIT_NAT_SRV_PASS           1067
#define IDC_NAT_SRV_CONNECT_GROUP       1068
#define IDC_NAT_SRV_CONNECT             1069
#define IDC_EDIT_NAT_SRV_CONNECT        1070
#define IDC_NAT_SRV_PEER                1071
#define IDC_EDIT_NAT_SRV_PEER           1072
#define IDC_NAT_CIPHER_GROUP            1073
#define IDC_NAT_COMPRESSION_GROUP       1074
#define IDC_NAT_KEY_GROUP               1075
#define IDC_RADIO_NAT_CIPH_NONE         1076
#define IDC_RADIO_NAT_CIPH_AES_128      1077
#define IDC_RADIO_NAT_CIPH_AES_256      1078
#define IDC_RADIO_NAT_3DES              1079
#define IDC_RADIO_NAT_CIPH_RC4_128      1080
#define IDC_RADIO_NAT_COMP_NONE         1081
#define IDC_RADIO_NAT_COMP_ZLIB         1082
#define IDC_RADIO_NAT_COMP_LZO          1083
#define IDC_RADIO_NAT_KX_PSK            1084
#define IDC_RADIO_NAT_KX_DHE_PSK        1085
#define IDC_NAT_CONTROL_GROUP           1086
#define IDC_NAT_TIMEOUT                 1087
#define IDC_EDIT_NAT_TIMEOUT            1088
#define IDC_BUTTON_NAT_CONNECT          1089
#define IDC_BUTTON_NAT_DISCONNECT       1090
#define IDC_NAT_CREDENTIALS_GROUP       1091
#define IDC_NAT_USER_ID                 1092
#define IDC_EDIT_NAT_USER_ID            1093
#define IDC_NAT_USER_KEY                1094
#define IDC_EDIT_NAT_USER_KEY           1095
#define IDC_NAT_DATA_GROUP              1096
#define IDC_EDIT_NAT_SEND_TEXT          1097
#define IDC_BUTTON_NAT_SEND             1098
#define IDC_BUTTON_NAT_CLEAR            1099
#define IDC_CHECK_NAT_ADD_BRAKLINE      1100
#define IDC_LIST_NAT_SEND               1101
#define IDC_LIST_NAT_RECEIVE            1102
#define IDC_NAT_SET_GROUP               1103
#define IDC_NAT_SRV_REMOTE_PEER         1104
#define IDC_EDIT_NAT_SRV_PEER2          1105
#define IDC_EDIT_NAT_SRV_REMOTE_PEER    1105
#define IDC_EDIT_NAT_AUTH_DELAY         1106
#define IDC_EDIT_NAT_AUTH_MAX           1107
#define IDC_EDIT_NAT_BIND_DELAY         1108
#define IDC_EDIT_NAT_BIND_MAX           1109
#define IDC_EDIT_NAT_PROBE_DELAY        1110
#define IDC_EDIT_NAT_PROBE_MAX          1111
#define IDC_EDIT_NAT_PORT_RANGE         1112
#define IDC_NAT_AUTH_DELAY              1113
#define IDC_NAT_AUTH_MAX                1114
#define IDC_NAT_BIND_DELAY              1115
#define IDC_NAT_BIND_MAX                1116
#define IDC_NAT_PROBE_DELAY             1117
#define IDC_NAT_PROBE_MAX               1118
#define IDC_NAT_PORT_RANGE              1119
#define IDC_CHECK_NAT_MASTER            1120
#define IDC_SERVER_USERID_EDIT          1121
#define IDC_NAT_SRV_REMOTE_PEER2        1121
#define IDC_SERVER_PASSWORD_EDIT        1122
#define IDC_EDIT_NAT_SRV_SESSION_ID     1122
#define IDC_CAPTION_STATIC              1123
#define IDC_CONNECT_TIMEOUT_EDIT        1123
#define IDC_PROGRESS1                   1124
#define ID_ABORT                        1126
#define IDC_CHECK1                      1127
#define IDC_ASYNC_CONNECT_CHECK         1127
#define IDC_CHECK2                      1128
#define IDC_CUSTOM_PORT_CHECK           1128
#define IDC_CUSTOM_PORT_EDIT            1129
#define ID_COMMANDS_CLEARLOG            32771
#define ID_COMMANDS_SAVELOGTOFILE       32772

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        135
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         1130
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
