//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SupportCenter.rc
//
#define IDD_SupportMessenger_DIALOG     102
#define IDR_HTML_SupportMessenger_DIALOG 104
#define IDR_HTML_INDEX                  105
#define IDR_HTML_ALERT                  106
#define IDR_HTML_SETTINGS               107
#define IDR_HTML_IE6NOTIF_MSG           108
#define IDR_HTML_TEAMVIEWERINSTALL_MSG  109
#define IDR_MAINFRAME                   128
#define IDR_TRAY_MENU                   130
#define IDS_INFO_UNATTENDED_CALLS_IN_INBOX 131
#define IDS_INFO_SNOOZING_CALLS_IN_INBOX 132
#define IDI_AVAILIBLE                   132
#define IDS_INFO_CALL_WAS_TAKEN_CANNOT_SNOOZED 133
#define IDI_NOT_ACCEPTING_CALLS         133
#define IDS_ERROR_USERNAME_UNKNOWN      134
#define IDI_BUSY                        134
#define IDS_INFO_CONNECTION_TEST_TAB    134
#define IDS_ERROR_PASSWORD_INCORRECT    135
#define IDI_AWAY                        135
#define IDS_INFO_CHANGING_USER_FLAG     136
#define IDI_OFFLINE                     136
#define IDI_MYSTATUS_OFFLINE            136
#define IDS_ERROR_SETTINGS_SHOWAWAY_NOT_CORRECT 136
#define IDI_NEWCALLS                    137
#define IDS_MENU_ITEM_OPEN_TEXT_ONE_NEW_CALL 137
#define IDI_CONNECTING                  138
#define IDS_MENU_ITEM_OPEN_TEXT_X_NEW_CALLS 138
#define IDI_NEWCALLANIMATED2            139
#define IDS_TRAY_ICON_TOOLTIP_CONNECTING 139
#define IDI_ICON1                       140
#define IDI_NEWCALLANIMATED1            140
#define IDS_ERROR_PASSWORD_MISSEED      140
#define IDS_ERROR_USERNAME_MISSED       141
#define IDB_BITMAP_STATUS_AVAILIBLE     142
#define IDS_STRING142                   142
#define IDS_ERROR_ALREADY_SIGNEDIN      142
#define IDS_ERROR_AUTHENTICATION_FAILED 143
#define IDS_ERROR_CONNECT_FAILED        144
#define IDS_ERROR_CONFIG_PORT_WITH_UPNP_FAILED 144
#define IDB_BITMAP_STATUS_NOT_ACCEPTING_CALLS 145
#define IDS_STRING145                   145
#define IDS_ERROR_CONNECT_FAILED_LAST_ATTEPMT 145
#define IDB_BITMAP_STATUS_BUSY          146
#define IDS_ERROR_YOU_ARE_SIGNIN_ON_ANOTHER_COMPUTER 146
#define IDB_BITMAP_STATUS_AWAY          147
#define IDS_STRING147                   147
#define IDS_UPGRADE_ALERT_TEXT          147
#define IDB_BITMAP_STATUS_OFFLINE       148
#define IDS_ERROR_ERROR_CODE_PREFIX     148
#define IDS_STRING149                   149
#define IDS_INFO_MSG_UPDATE_SUCCESSFULLY_COMPLETED 149
#define IDS_ERROR_TEST_FAILED           150
#define IDS_ERROR_TEST_SUCCESSED        151
#define IDS_ERROR_YOU_MAYBE_AUTHENTICATED_ONCE_ON_THIS_COMPUTER 152
#define IDI_I                           153
#define IDS_INFO_CALLS_IN_INSESSION     153
#define IDD_DIALOG1                     154
#define IDD_ALERT_DIALOG                154
#define IDS_MISSEDCALLS_ALERT_TEXT      154
#define IDB_BITMAP1                     155
#define IDS_MISSEDCALLS_OFFLINE_ALERT_TEXT 155
#define IDB_BITMAP2                     156
#define IDS_TRAY_ICON_TOOLTIP_IS_OFFLINE_DUE_IDLE 156
#define IDB_BITMAP3                     157
#define IDS_STRING157                   157
#define IDS_TRAY_ICON_TOOLTIP_CONNECTED_NOT_AVAILIBLE 157
#define IDB_BITMAP4                     158
#define IDS_WARNING_CLOSE_WORKBENCH     158
#define IDD_DIALOG2                     159
#define IDD_SETTINGS_DIALOG             159
#define IDS_STRING159                   159
#define IDS_ERROR_IE7_VERSION_REQUIRED  159
#define IDI_ICON2                       160
#define IDS_TRAY_ICON_TOOLTIP_LIMITED_CONNECTION 160
#define IDS_TRAY_ICON_TOOLTIP_LIMITED_CONNECTION_IMPROVED 161
#define IDS_TRAY_ICON_TOOLTIP_AVAILIBLE_LIMITED_CON 162
#define IDW_WAVE_MESSAGE                163
#define IDW_WAVE_ONPICKUP               164
#define IDR_WAV1                        166
#define IDI_NEW_CALLS                   169
#define IDI_UPDATE_REQUIRED             170
#define IDI_ICON3                       171
#define IDI_NEWCALLANIMATED3            171
#define IDS_TRAY_ICON_TOOLTIP_X_NEW_CALLS 172
#define IDS_TRAY_ICON_TOOLTIP_ONE_NEW_CALL 173
#define IDI_CONNECTINGANIMATED1         173
#define IDS_TRAY_ICON_TOOLTIP_AVAILIBLE 174
#define IDI_ICON5                       174
#define IDI_CONNECTINGANIMATED2         174
#define IDS_TRAY_ICON_TOOLTIP_BUSY      175
#define IDD_DIALOG3                     175
#define IDD_WORKBENCH_DIALOG            175
#define IDI_MYSTATUS_AVAILIBLE_LIMITED_CON 175
#define IDS_TRAY_ICON_TOOLTIP_AWAY      176
#define IDD_DIALOG4                     176
#define IDD_ONLINE4CUSTOMER_DIALOG      176
#define IDI_MYSTATUS_AWAY_LIMITED_CON   176
#define IDS_TRAY_ICON_TOOLTIP_OFFLINE   177
#define IDI_MYSTATUS_BUSY_LIMITED_CON   177
#define IDS_TRAY_ICON_TOOLTIP_NEW_CALL_ANIMATION 178
#define IDI_MYSTATUS_OFFLINE_LIMITED_CON 178
#define IDS_TRAY_ICON_TOOLTIP_UPDATE_REQUIRED 179
#define IDI_MYSTATUS_ONNLINEFORCUSTOMER1 179
#define IDI_MYSTATUS_ONNLINEFORCUSTOMER_LIMITED_CON 179
#define IDS_TRAY_ICON_TOOLTIP_IS_SIGNEDIN 180
#define IDS_TRAY_ICON_TOOLTIP_IS_SIGNEDOUT 181
#define IDS_MENU_ITEM_OPEN_TEXT         182
#define IDS_MENU_ITEM_SIGNOUT_TEXT      183
#define IDS_MENU_ITEM_SIGNIN_TEXT       184
#define IDS_APP_FULL_NAME               185
#define IDS_TRAY_ICON_TOOLTIP_ONNLINE4CUSTOMER 186
#define IDD_DHTMLDIALOG_MSG             187
#define IDS_TRAY_ICON_TOOLTIP_BUSY_LIMITED_CON 190
#define IDS_TRAY_ICON_TOOLTIP_AWAY_LIMITED_CON 191
#define IDS_TRAY_ICON_TOOLTIP_OFFLINE_LIMITED_CON 192
#define IDS_TRAY_ICON_TOOLTIP_ONNLINE4CUSTOMER_LIMITED_CON 193
#define ID_OPEN_DOCK                    32771
#define ID_POPUP_DOCK                   32772
#define ID_OPEN                         32773
#define ID_POPUP_OPEN                   32774
#define ID_DOCK_RIGHT                   32775
#define ID_DOCK_LEFT                    32776
#define ID_POPUP_MYSTATUS               32777
#define ID_POPUP_SETTINGS               32778
#define ID_POPUP_VIEWHISTORY            32779
#define ID_POPUP_LINKS                  32780
#define ID_POPUP_HELP                   32781
#define ID_POPUP_SINGOUT                32782
#define ID_POPUP_EXIT                   32783
#define IDI_MYSTATUS_AVAILIBLE          32784
#define IDI_MYSTATUS_NOTACCEPTINGCALLS  32785
#define IDI_MYSTATUS_AWAY               32786
#define IDI_MYSTATUS_BUSY               32787
#define ID_LINKS_MYACCOUNT              32788
#define ID_LINKS_MYPROFILE              32789
#define ID_LINKS_LIBRARY                32790
#define ID_LINKS_SUPPORTERSCAFE         32791
#define ID_LINKS_SUPPORTSPACEHOMEPAGE   32792
#define ID_HELP_HELP                    32793
#define ID_HELP_ABOUT                   32794
#define ID_POPUP_TABSVIEW               32795
#define ID_POPUP_CLEAREVENTS            32796
#define ID_HELP_ABOUT32798              32798
#define ID_POPUP_SIGNIN                 32799
#define ID_LINKS_EXPERTFORUM            32801
#define IDI_MYSTATUS_ONNLINEFORCUSTOMER 32802
#define ID_LINKS_SESSIONSHISTORY        32803
#define ID_LINKS_EXPERTPORTAL           32804
#define ID_LINKS_MYMESSAGES             32805

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        192
#define _APS_NEXT_COMMAND_VALUE         32806
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
