//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by RCTest2.rc
//
#define IDD_RCTEST2_DIALOG              102
#define IDR_MAINFRAME                   128
#define IDD_ADD_CLIENT_DIALOG           129
#define IDD_ADD_VIEWER_DIALOG           130
#define IDD_VIEWER_DIALOG               131
#define IDR_VIEWER_MENU                 132
#define IDD_NET_SETTINGS                133
#define IDD_PROGRESS_DLG                134
#define IDB_CURSOR                      135
#define IDB_CURSOR_LC                   136
#define IDB_CURSOR_RC                   137
#define IDD_FAKED_CHAT                  138
#define IDC_ADD_CLIENT_BTN              1000
#define IDC_EDIT_IP                     1000
#define IDC_ADD_VIEWER_BTN              1001
#define IDC_EDIT_DEST_PORT              1001
#define IDC_LOG_LIST                    1002
#define IDC_BUTTON_CONNECT              1002
#define IDC_KILL_CLIENT_BTN             1003
#define IDC_EDIT_LOCAL_PORT             1003
#define IDC_CLIENTS_LIST                1004
#define IDC_BUTTON_ACCEPT               1004
#define IDC_EDIT_SOURCE_PEER            1004
#define IDC_VIEW_ONLY                   1005
#define IDC_BUTTON_SHADOW_STREAM        1005
#define IDC_VISUAL_POINTER              1006
#define IDC_BUTTON_CREATE_FROM_SHADOW_STREAM 1006
#define IDC_PROTECT_WINDOW              1007
#define IDC_EDIT_DEST_PEER              1007
#define IDC_CLEAR_LOG_BTN               1008
#define IDC_BUTTON_CONNECT2             1008
#define IDC_SET_SHADOW_STREAM_BTN       1009
#define IDC_BUTTON_RESET_SERVER         1009
#define IDC_NETSETTINGS_BTN             1010
#define IDC_EDIT_DEST_PEER2             1010
#define IDC_EDIT_SESSION_ID             1010
#define IDC_KILL_CLIENT_BTN2            1011
#define IDC_SEND_GARBAGE_BTN            1011
#define IDC_CHAT_EMULATOR_BTN           1012
#define IDC_COMBO1                      1013
#define IDC_DISPLAY_MODE_COMBO          1013
#define IDC_VIEW_ONLY_CHECK             1014
#define IDC_VISUAL_POINTER_CHECK        1015
#define IDC_CHECK1                      1015
#define IDC_AUTO_ACCEPT_CHECK           1015
#define IDC_ZRLE_RADIO                  1016
#define IDC_ZLIBXOR_RADIO               1017
#define IDC_ZLIBHEX_RADIO               1018
#define IDC_HEXTILE_RADIO2              1019
#define IDC_RRE_RADIO                   1020
#define IDC_CoRRE_RADIO                 1021
#define IDC_RAW_RADIO                   1022
#define IDC_Ultra_RADIO                 1023
#define IDC_TIGHT_RADIO                 1024
#define IDC_COPYRECT_CHECK              1025
#define IDC_FULL_RADIO                  1026
#define IDC_256CLR_RADIO                1027
#define IDC_64CLR_RADIO                 1028
#define IDC_8CLR_RADIO2                 1029
#define IDC_8DARKCLR_RADIO2             1030
#define IDC_4GRAYCLR_RADIO2             1031
#define IDC_BWCLR_RADIO                 1032
#define IDC_CACHEENC_CHECK              1033
#define IDC_ZIPTIGHT_CHECK              1034
#define IDC_JPEGQ_CHECK                 1035
#define IDC_ZIPCOMPRESSION_EDIT         1036
#define IDC_JPEGQ_EDIT                  1037
#define IDC_AUTODETECT_CHECK            1038
#define IDC_ENCODING_STATIC             1039
#define IDC_COLORS_STATIC               1040
#define IDC_RELAY_EDIT                  1041
#define IDC_VIEW_ONLY_CHECK2            1041
#define IDC_LAYEREDCAPTURE_CHECK        1041
#define IDC_PROGRESS1                   1042
#define IDC_USERID_EDIT                 1042
#define IDC_CAPTION_STATIC              1043
#define IDC_PASSWORD_EDIT2              1043
#define IDC_PASSWORD_EDIT               1043
#define IDC_STUNPORT_EDIT               1044
#define IDC_CHAT_CHATBOARD              1044
#define IDC_RELAYPORT_EDIT              1045
#define IDC_CHAT_SENDLINE               1045
#define IDC_RELAYPORT_EDIT2             1046
#define IDC_IMSTUBPORT_EDIT             1046
#define IDC_CHAT_SMILESAD               1046
#define IDC_CHAT_SMILEGLAD              1047
#define IDC_CHAT_SENDBUTTON             1048
#define IDC_CHAT_SMILENEUTRAL           1049
#define IDC_CHAT_SMILEGLASSES           1050
#define IDC_CHAT_SMILECRAZY             1051
#define IDC_CHAT_SMILELOL               1052
#define IDC_CHAT_SMILELOL2              1053
#define IDC_CHAT_CLOSE                  1053
#define ID_COMMANDS_START               32771
#define ID_COMMANDS_STOP                32772
#define ID_OPTIONS_VIEWONLY             32773
#define ID_OPTIONS_VISUALPOINTER        32774
#define ID_OPTIONS_SCALEMODE            32775
#define ID_OPTIONS_FULLSCREENMODE       32776
#define ID_OPTIONS_SCROLLMODE           32777
#define ID_REPLAY_START                 32778
#define ID_REPLAY_STOP                  32779
#define ID_REPLAY_PAUSE                 32780
#define ID_REPLAY_FASTFORWARD           32781
#define ID_FASTFORWARD_X1               32782
#define ID_FASTFORWARD_X2               32783
#define ID_FASTFORWARD_X4               32784
#define ID_FASTFORWARD_X8               32785
#define ID_FASTFORWARD_X20              32786
#define ID_REPLAY_FASTBACKWARD          32787
#define ID_FASTBACKWARD_1X              32788
#define ID_FASTBACKWARD_2X              32789
#define ID_FASTBACKWARD_X3              32790
#define ID_FASTBACKWARD_X               32791
#define ID_FASTBACKWARD_X20             32792
#define ID_FASTFORWARD_FASTEST          32793
#define ID_OPTIONS_ZOOM                 32794
#define ID_ZOOM_STRETCHING              32795
#define ID_OPTIONS_SETSHADOWSTREAM      32796
#define ID_COMMANDS_SENDCTRL            32797
#define ID_COMMANDS_SENDGARBAGEINTOSTREAM 32798

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        139
#define _APS_NEXT_COMMAND_VALUE         32799
#define _APS_NEXT_CONTROL_VALUE         1053
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
