#include "adddevice.h"
#include "..\public\user.h"
#include "common.h"

#ifdef ALLOC_PRAGMA
#pragma alloc_text (PAGE, OnAddDevice)
#endif

NTSTATUS OnAddDevice(
	IN PDRIVER_OBJECT  DriverObject,
	IN PDEVICE_OBJECT  PDO
)
{
    UNICODE_STRING      KbrdDeviceName;
	NTSTATUS            Status = STATUS_SUCCESS;
	PDEVICE_OBJECT		LowerKbrdDeviceObject;
	PDEVICE_OBJECT		LowerMouseDeviceObject;
	PFILE_OBJECT		FileObject;
	PDEVICE_EXTENSION	drvExt;


	do 
	{
	
		Status = IoCreateDevice(
								DriverObject,
								sizeof(DEVICE_EXTENSION),
								NULL,
								FILE_DEVICE_MOUSE,
								FILE_AUTOGENERATED_DEVICE_NAME,
								FALSE,
								&LowerMouseDeviceObject);

	   if(!NT_SUCCESS(Status))
		{
			DbgPrint("OnAddDevice: failed to create mouse device: %d\n", Status);
			break;
		}

   
		DbgPrint("OnAddDevice: mouse device created\n");

		drvExt = (PDEVICE_EXTENSION)LowerMouseDeviceObject->DeviceExtension;

		drvExt->Top_of_Mouse_Stack = IoAttachDeviceToDeviceStack(LowerMouseDeviceObject, PDO);
		if (drvExt->Top_of_Mouse_Stack == NULL) 
		{
			DbgPrint("OnAddDevice: failed to attach device: %d\n", Status);
			IoDeleteDevice(LowerMouseDeviceObject);
			break;
	    }	
		drvExt->HookMouseDeviceObject = LowerMouseDeviceObject;
		drvExt->HookMouseDeviceObject->Flags |= (DO_BUFFERED_IO | DO_POWER_PAGABLE);
		drvExt->HookMouseDeviceObject->Flags &= ~DO_DEVICE_INITIALIZING;
		drvExt->UpperConnectData.ClassService = NULL;

		//Status = IoAttachDevice(drvExt->HookMouseDeviceObject,&MouseDeviceName ,&drvExt->Top_of_Mouse_Stack);
	
		Status = IoRegisterDeviceInterface(
                PDO,
                &InterfaceClassGuidConstant,
                NULL,
                &drvExt->DeviceLinkName
                );
		//TODO: Free Symbolic Link
		if (!NT_SUCCESS(Status)) 
		{
			DbgPrint("OnAddDevice: failed to Register Device Interface: %d\n", Status);
			IoDeleteDevice(drvExt->HookMouseDeviceObject);
			break;
	    }
	
		DbgPrint("OnAddDevice: Device is attached to mouse device\n");


		RtlInitUnicodeString(&KbrdDeviceName, KEYBOARD_DEVICE);

		Status = IoCreateDevice(
								DriverObject,
								0,
								NULL,
								FILE_DEVICE_KEYBOARD,
								0,
								FALSE,
								&drvExt->HookKbrdDeviceObject);

		if(!NT_SUCCESS(Status))
		{
			DbgPrint("OnAddDevice: failed to create keyboard device: %d\n", Status);
			IoDeleteDevice(drvExt->HookMouseDeviceObject);
			break;
		}

		drvExt->HookKbrdDeviceObject->Flags |= DO_BUFFERED_IO;
		drvExt->HookKbrdDeviceObject->Flags &= ~DO_DEVICE_INITIALIZING;

		DbgPrint("OnAddDevice: keyboard device created\n");

	//	Status = IoAttachDevice(drvExt->HookKbrdDeviceObject, &KbrdDeviceName, &drvExt->Top_of_KBD_Stack);

		if(!NT_SUCCESS(Status))
		{
			DbgPrint("OnAddDevice: failed to attach device: %d\n", Status);
			IoDeleteDevice(drvExt->HookMouseDeviceObject);
			IoDeleteDevice(drvExt->HookKbrdDeviceObject);
			break;
		}
		DbgPrint("OnAddDevice: Device is attached to keyboard device\n");

	} while (FALSE);


	InputDisabled = FALSE;
	DriverOpened = FALSE;
	WaitTimeout.QuadPart = -300000000;

	KeInitializeSpinLock(&KbrdQueueLock);
	InitializeListHead(&KbrdQueue);
	KbrdQueueSize = KBRD_QUEUE_SIZE;
	KbrdQueueCount = 0;
	KeInitializeEvent(&KbrdEvent, SynchronizationEvent, FALSE);


	KeInitializeSpinLock(&MouseQueueLock);
	InitializeListHead(&MouseQueue);
	MouseQueueSize = MOUSE_QUEUE_SIZE;
	MouseQueueCount = 0;
	KeInitializeEvent(&MouseEvent, SynchronizationEvent, FALSE);

	MouseBufferSize = MOUSE_BUFFER_SIZE;
	MouseBufferCount = 0;
	MouseRelX = 0;
	MouseRelY = 0;
	MouseButtons = 0;
	MouseFirstPacket = TRUE;

	return Status;

/*
	NTSTATUS			Status;
	OBJECT_ATTRIBUTES	Attributes;
	HANDLE             	FileHandle;
	IO_STATUS_BLOCK    	IOStatus;
	PDEVICE_OBJECT		DeviceObject;
	PDEVICE_OBJECT		MouseDeviceObject;
	PFILE_OBJECT		FileObject;
	UNICODE_STRING		DeviceName;

	DbgPrint("MegaDriver: Attach start\n");

	RtlInitUnicodeString(&DeviceName, MOUSE_DEVICE);

	InitializeObjectAttributes(&Attributes, &DeviceName, OBJ_CASE_INSENSITIVE, NULL, NULL);
	DbgPrint("MegaDriver: InitializeObjectAttributes\n");

	Status = ZwCreateFile(
		&FileHandle,
		SYNCHRONIZE | FILE_ANY_ACCESS,
		&Attributes,
		&IOStatus,
		NULL,
		0,
		FILE_SHARE_READ | FILE_SHARE_WRITE,
		FILE_OPEN,
		FILE_SYNCHRONOUS_IO_NONALERT,
		NULL,
		0);

	DbgPrint("MegaDriver: ZwCreateFile\n");

//	RtlFreeUnicodeString(&DeviceName);

	DbgPrint("MegaDriver: RtlFreeUnicodeString\n");

	if(!NT_SUCCESS(Status))
	{
		DbgPrint("MegaDriver: Cannot ZwCreateFile: %d\n", Status);
		return Status;
	}

	Status = ObReferenceObjectByHandle(
		FileHandle,
		FILE_READ_DATA,
		NULL,
		KernelMode,
		&FileObject,
		NULL);

	if(!NT_SUCCESS(Status))
	{
		DbgPrint("MegaDriver: Failed ObReferenceObjectByHandle\n");
		ZwClose(FileHandle);
		return Status;
	}

	MouseDeviceObject = IoGetRelatedDeviceObject(FileObject);

	if(!MouseDeviceObject)
	{
		DbgPrint("MegaDriver: Failed IoGetRelatedDeviceObject\n");
		ZwClose(FileHandle);
		return STATUS_OBJECT_TYPE_MISMATCH;
	}

	DeviceObject = IoAttachDeviceToDeviceStack(fdo, MouseDeviceObject);

	((PDEVICE_EXTENSION)fdo->DeviceExtension)->TopOfStack = DeviceObject;
	DbgPrint("MegaDriver: TopOfStack established: %d\n", ((PDEVICE_EXTENSION)fdo->DeviceExtension)->TopOfStack);

	if(!DeviceObject)
	{
		DbgPrint("MegaDriver: Failed IoAttachDeviceByPointer\n");
		ZwClose(FileHandle);
		return Status;
	}

	return STATUS_SUCCESS;
	*/
	DbgPrint("OnAddDevice: Leave\n");

	return STATUS_SUCCESS;
}

